[package]
name = "getweb"
version = "0.1.0"
edition = "2021"

[dependencies]
playwright = "0.0.20"
# playwright = { git = "https://github.com/octaltree/playwright-rust", branch = "1.25"}
tokio = "1.32.0"
clap = { version = "4.4.6", features = ["derive"] }

